### ISSUE TITLE
Fix dependabot for Gradle

### ISSUE THREAD

**Issue by binkley** [binkley/modern-java-practices#498]
See #533 for a breakup of this work. The remaining 2 tasks are special cases.

### Questions
- Do other tools understand the Gradle version catalog? For example, DependencyCheck
   - Answer: Yes. DependencyCheck, checking for updates, all seem to work with Gradle API, and are fine with the version catalog (so far)

### Tasks
- [x] Working example for one dependency using Gradle catalog instead of properties
- [x] Migrate remaining dependencies to catalog from properties
- [x] Working example of one plugin using Gradle catalog instead of properties
- [x] Migrate "easy" plugins to catalog from properties
- [ ] Migrate "complicated" 3rd-party plugins to catalog from properties (these have separate tool version from plugin, and/or have naming conflicts between libraries and plugin)
- [ ] Migrate plugins that ship with Gradle
- [x] Gradle versions plugin "sees" catalog, and shows outdated dependencies & plugins -- resolve `dependencyUpdates` task not working
- [x] Update docs for managing Gradle versions and GitHub dependabot (including changelog)
- [x] GitHub Dependabot sees catalog, and creates PRs for Gradle dependency/plugin updates

### Out of scope

Migrating writing to the new "Dependency management page".

### Acceptance criteria

- [x] Wait for GitHub dependabot to file a PR for a Gradle dependency update.
   **This works nicely**, and we've been getting PRs from GitHub for Gradle dependencies that are migrated.
- [x] Docs are updated to talk about the Gradle version catalog, and using that with Dependabot. Mirror the conversation for Maven with Dependabot

### Observations
- Dependabot files PRs for Maven dependency updates
- Dependabot **does not** file PRs for Gradle dependency updates

### Root cause
Dependabot does not process `build.gradle` like a Gradle build does, so abstracting version properties to `gradle.properties` does not work.

### Resolution
Use the Gradle version catalog in `gradle/libs.versions.toml` rather than `gradle.properties` + `settings.gradle` for version management.
Older versions of Gradle relied on props & settings, but Gradle has moved to using the TOML file for this purpose.

### See
- https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#gradle
- `compare-tooling-versions.sh` script in the repo, presently a fiddly workaround to spot when Maven gets ahead of Gradle for common dependency and tool versions. The script approach is both (1) manual, and (2) does not scale
- https://github.com/littlerobots/version-catalog-update-plugin
- https://developer.android.com/build/migrate-to-catalogs

**Comment by binkley** [comment]
Basic problem that slowed down the card:
Gradle version catalogs are a new feature in gradle -- experimental in 7, finalized in 8 -- and the online example are either:
- Sparse
- Using Gradle 7, which doesn't work with Gradle 8
- Focused on the Android ecosystem

I got around this when I found a nice Gradle plugin to manage catalog versions, and includes creating a new setup for you based on your existing code & versions.

**Comment by binkley** [comment]
Link for docs showing how to use a catalog version when seeing a plugin `toolVersion`: https://docs.gradle.org/current/userguide/platforms.html#ex-using-a-version-declared-in-a-version-catalog. You do not need the `.get()` part.

**Comment by binkley** [comment]
In docs note that Maven keeps everything in one file (`pom.xml`) and Gradle spreads it around.

**Comment by binkley** [comment]
Note that the JaCoCo version _might_ be hard-set regardless of project settings. Follow up on this to check.
https://github.com/gradle/gradle/blob/master/platforms/jvm/jacoco/src/main/java/org/gradle/testing/jacoco/plugins/JacocoPlugin.java#L73

**Comment by binkley** [comment]
Gradle comes with some plugins "baked in" such as _Checkstyle_.
This changes the approach in other config files when using the version catalog.
