### ISSUE TITLE
Align code CONTRIBUTING.MD and wiki Contributing.md

### ISSUE THREAD

**Issue by binkley** [binkley/modern-java-practices#529]
The code version of `CONTRIBUTING.md` has a lot of detail to help folks reuse the project whereas the wiki version of `Contributing.md` is about authorship.

## Tasks
- [ ] Decide if these pages need aligning, ie, the wiki version should be more like the code version.
   Logically, wiki page authors and code contributors are distinct.
- [ ] Wiki page for contributors should acknowledge those who contributed PRs to the code example. 
- [ ] Automate this if possible and sensible.

## Refs
- See #530 for another automation card in the code repo
