### ISSUE TITLE
Document Spotless

### ISSUE THREAD

**Issue by binkley** [binkley/modern-java-practices#535]
See #462 for the epic.
The card is marked MVP as it is in progress. Remove the "mvp" label if that makes sense.

### Context

Show Spotless in the Gradle and Maven build even though Checkstyle remains the example default.
So both Gradle & Maven have flags/settings that do not run Spotless, but you can still run them specifically on the command line.

### Tasks for this story
- [x] 1. ~~Configure for Gradle and Maven to format the same as Checkstyle (but Spotless still disabled as a default) .~~
- [x] 2. Document both Checkstyle and Spotless as options in Gradle and Maven; the project should keep defaulting to Checkstyle.  Do not promote a particular style. <-- **should we switch to Spotless? We've chatted before on this, and I am still on the fence**
- [ ] 3. If feasible, show how to set up alternative styles (like how Checkstyle does with files). With Gradle & Maven, it is one-liners to change the style.
- [x] 4. Writing layout and style should be common among the quality plugins. This is a good opportunity to set a common writing pattern so other plugins can follow Spotless/Checkstyle as a template.

I removed the first task: it is unreasonable for a book to deal with slight formatting changes; developers using the writing can figure that out. 😄 

### Acceptance criteria

**Scenario: Reading the book**
GIVEN the documentation in the book
WHEN a reader reads about code style checks
THEN there is an example in the book and example code for configuring Spotless to check style for both Gradle and Maven

**Comment by binkley** [comment]
Checkstyle current configuration file is less lenient that Spotless.
An example is that `{}' is OK with Checkstyle but Spotless wants `{ }' (note the space).
