### ISSUE TITLE
[Spike] Alternatives to Earthly for containerized builds

### ISSUE THREAD

**Issue by binkley** [binkley/modern-java-practices#545]
### Context

Originally the build was based on [Batect](https://batect.dev/) for containerized builds; however that project is [no longer maintained[(https://github.com/batect/batect) by its author.

This project has moved to [Earthly](https://github.com/earthly/earthly) that is well-maintained. However, it currently has some features that [may interact poorly](https://docs.earthly.dev/docs/earthfile#project) depending on project setup and configuration.

An obvious approach is a plain Docker container (something that both Batect and Earthly both use under the hood). Since we rely on Gradle and Maven, and plugins are the key for build quality, the 3rd-party wrappers may not offer enough value to be the default.

### Tasks

- [ ] Research alternatives to Earthly, and decide which should be documented
- [ ] Provide a plain `Dockerfile` for a containerized build easily used with local and CI builds
- [ ] Decide on: plain Docker files, or use the Earthly wrapper as the project default
- [ ] If changing to plain Docker, update doc pages to reflect that, and in one page talk about alternatives

**Comment by jbduncan** [comment]
I learned about https://github.com/flox/flox recently, which I understand from one of my colleagues is supposed to make Nix user-friendly.

**Comment by jbduncan** [comment]
Having said all this, I'm aware that you're a huge advocate of containerised builds for cross-environment reproducibility, so feel free to disregard my suggestions. 😉
