### ISSUE TITLE
[Do not implement] Add animal sniffer to build

### ISSUE THREAD

**Issue by binkley** [binkley/modern-java-practices#574]
**CLOSED** -- the animal sniffer project is not keeping up to date with recent JDK versions: most recent is Java 17.

Animal Sniffer is a Maven plugin to check your library's binary API usage against signatures of known projects, and validate that you provide through transitive dependencies at least version X of an API.

Some popular tools use this (such as the testing plugins for Maven), and it is a generally good hygiene practice for libraries and plugins.
It is not relevant to stand-alone applications not meant to be dependencies.

Principle examples are:

- JDK API for version X of Java
- API for other libraries that provide signature files

### Tasks
- [ ] Update example code to use Animal Sniffer against JDK 21
- [ ] Add animal sniffer to Maven build
- [ ] Research for Gradle equivalent
- [ ] Generate an API signature for the example project

Ref: https://www.mojohaus.org/animal-sniffer/animal-sniffer-maven-plugin/
