### ISSUE TITLE
Quiet PITest (mutation testing) output for local builds, but not for CI builds

### ISSUE THREAD

**Issue by binkley** [binkley/modern-java-practices#600]
Both the Gradle and Maven plugins for PITest have a `verbose` configuration option.
Spiking among the 4 cases (2 for Gradle/Maven; 2 for verbose true/false):
- Gradle plugin treats verbose true/false as regular build output
- Maven plugin treats verbose true/false as debug build output

## Tasks
- [x] Quiet Gradle regular build output in local
- [ ] Show Gradle regular build output in CI
- [ ] Quiet Maven regular build output in local
- [ ] Show Maven regular build output in CI
- [ ] Explore debug output

## Refs
- https://github.com/hcoles/pitest/issues/1338 - Maven PITest plugin issue discussing how to quiet regular output
