### ISSUE TITLE
Support javadoc generation in the build

### ISSUE THREAD

**Issue by binkley** [binkley/modern-java-practices#604]
While working on #483 and wanting to raise readability of the PR https://github.com/binkley/modern-java-practices/pull/601, I realized we are not capturing Javadoc for projects.

----

A successful project is not just the working code and build pipeline, but includes documentation for others (on your team, other teams, company internal, public). This helps you to:
- Onboard new contributors
- Share code internally
- Share code to the public
- Discuss code goals and APIs with manager roles

### Tasks
- [x] Generate Javadoc from project source using Gradle
- [x] Generate Javadoc from project source using Maven
- [x] Provide javadoc both as HTML locally, and as a jar to share with the project
- [x] Update GH builds to save Javadoc jars as build artifacts
- [x] Update wiki writing to explain and provide examples (including CI configuration)

### Add to the wiki page discussion
We provide _mechanism_, not _policy_ here:
* When to document and _not_ document code
* Discuss when unit test documentation is useful
* Discuss when integration test document is useful
   There are use cases that integration and higher-level testing provide documentation useful to users and business folks.

### References
- https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/storing-workflow-data-as-artifacts

**Comment by binkley** [comment]
The temporary image for the Documentation page is broken:
- It is not transparent
- Unclear on licensing

**Comment by binkley** [comment]
Example out put with Maven:
```
🌷 find target -name \*.jar
target/modern-java-practices-0-SNAPSHOT.jar
target/findsecbugs-plugin-1.13.0.jar
target/modern-java-practices-0-SNAPSHOT-test-javadoc.jar
target/modern-java-practices-0-SNAPSHOT-javadoc.jar
target/modern-java-practices-0-SNAPSHOT-jar-with-dependencies.jar
```

**Comment by binkley** [comment]
Example results with `./gradle clean build`
```
🌷 find build -name \*.jar
build/libs/modern-java-practices-0-SNAPSHOT.jar
build/libs/modern-java-practices-0-SNAPSHOT-javadoc.jar
build/tmp/.cache/expanded/zip_ff7bf8f04f99dc306508d1c81e47a68b/jacocoagent.jar
```
