### ISSUE TITLE
Move to a Creative Commons license

### ISSUE THREAD

**Issue by binkley** [binkley/modern-java-practices#606]
From conversation in Slack:

> Should we move from Public Domain to Creative Commons licensing?
> https://creativecommons.org/version4/
> The point about "A more global license" really appeals to me. Public Domain has issues in several key countries (eg, France and Italy where authors cannot give up their rights -- IANAL!). Based on some quick web searches, this is a partial list of countries where there may be problems: https://en.wikipedia.org/wiki/Moral_rights#Table
> If I guess at what the language involved means in those countries, moving to CC licensing protects the user, and that authors could potentially sue under PD.
> If I understand the reading, PD only applies once an author has expired.

### Tasks
- [x] Move code base to a CC0 license
- [x] Move wiki pages to a CC0 license
- [x] Update wiki home page, which still says the licensing is public domain
- [x] Why do we have sections explaining what the former license was?
